// <auto-generated />
using System;
using C_Sharp_Mini_Project_2;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;

#nullable disable

namespace CSharpMiniProject2.Migrations
{
    [DbContext(typeof(AssetDbContext))]
    [Migration("20221208212648_SetupDBs")]
    partial class SetupDBs
    {
        /// <inheritdoc />
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "7.0.0")
                .HasAnnotation("Relational:MaxIdentifierLength", 128);

            SqlServerModelBuilderExtensions.UseIdentityColumns(modelBuilder);

            modelBuilder.Entity("C_Sharp_Mini_Project_2.Computer", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<string>("Brand")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Model")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Office")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<int>("Price")
                        .HasColumnType("int");

                    b.Property<DateTime>("Purchase_date")
                        .HasColumnType("datetime2");

                    b.HasKey("Id");

                    b.ToTable("computers");

                    b.HasData(
                        new
                        {
                            Id = 1,
                            Brand = "HP",
                            Model = "Elitebook",
                            Office = "Spain",
                            Price = 1423,
                            Purchasedate = new DateTime(2022, 5, 1, 0, 0, 0, 0, DateTimeKind.Unspecified)
                        },
                        new
                        {
                            Id = 2,
                            Brand = "HP",
                            Model = "Elitebook",
                            Office = "Sweden",
                            Price = 588,
                            Purchasedate = new DateTime(2019, 10, 7, 0, 0, 0, 0, DateTimeKind.Unspecified)
                        },
                        new
                        {
                            Id = 3,
                            Brand = "Asus",
                            Model = "W234",
                            Office = "USA",
                            Price = 1200,
                            Purchasedate = new DateTime(2019, 7, 21, 0, 0, 0, 0, DateTimeKind.Unspecified)
                        },
                        new
                        {
                            Id = 4,
                            Brand = "Lenovo",
                            Model = "Yoga 730",
                            Office = "USA",
                            Price = 835,
                            Purchasedate = new DateTime(2019, 9, 28, 0, 0, 0, 0, DateTimeKind.Unspecified)
                        },
                        new
                        {
                            Id = 5,
                            Brand = "Lenovo",
                            Model = "Yoga 530",
                            Office = "USA",
                            Price = 1030,
                            Purchasedate = new DateTime(2019, 11, 21, 0, 0, 0, 0, DateTimeKind.Unspecified)
                        });
                });

            modelBuilder.Entity("C_Sharp_Mini_Project_2.Phone", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<string>("Brand")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Model")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Office")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<int>("Price")
                        .HasColumnType("int");

                    b.Property<DateTime>("Purchase_date")
                        .HasColumnType("datetime2");

                    b.HasKey("Id");

                    b.ToTable("phones");

                    b.HasData(
                        new
                        {
                            Id = 1,
                            Brand = "iPhone",
                            Model = "8",
                            Office = "Spain",
                            Price = 970,
                            Purchasedate = new DateTime(2019, 11, 5, 0, 0, 0, 0, DateTimeKind.Unspecified)
                        },
                        new
                        {
                            Id = 2,
                            Brand = "iPhone",
                            Model = "11",
                            Office = "Spain",
                            Price = 990,
                            Purchasedate = new DateTime(2022, 4, 25, 0, 0, 0, 0, DateTimeKind.Unspecified)
                        },
                        new
                        {
                            Id = 3,
                            Brand = "iPhone",
                            Model = "X",
                            Office = "Sweden",
                            Price = 1245,
                            Purchasedate = new DateTime(2019, 8, 5, 0, 0, 0, 0, DateTimeKind.Unspecified)
                        },
                        new
                        {
                            Id = 4,
                            Brand = "Motorola",
                            Model = "Razr",
                            Office = "Sweden",
                            Price = 970,
                            Purchasedate = new DateTime(2019, 9, 6, 0, 0, 0, 0, DateTimeKind.Unspecified)
                        });
                });
#pragma warning restore 612, 618
        }
    }
}
